### ISSUE TITLE
Tìm dữ liệu về sản phẩm

### ISSUE THREAD

**Issue by hawkin-dono** [minhkhai2897/DungeonRush#4]
- Tìm dữ liệu về sản phẩm của các sàn thương mại điện tử: amazon, shoppee, lazada,….
- Yêu cầu về data:
    - Có ảnh
    - Có mô tả
    - Có loại sản phẩm

**Comment by thelong9** [comment]
[crawled_data_dien_thoai_may_tinh_bang.csv](https://github.com/minhkhai2897/BTL_cong_nghe_phan_mem/files/14646422/crawled_data_dien_thoai_may_tinh_bang.csv)
[crawled_data_do_choi_me_be.csv](https://github.com/minhkhai2897/BTL_cong_nghe_phan_mem/files/14646423/crawled_data_do_choi_me_be.csv)
[crawled_data_nha_cua_doi_song.csv](https://github.com/minhkhai2897/BTL_cong_nghe_phan_mem/files/14646424/crawled_data_nha_cua_doi_song.csv)
[crawled_data_thiet_bi_kts_phu_kien_so.csv](https://github.com/minhkhai2897/BTL_cong_nghe_phan_mem/files/14646425/crawled_data_thiet_bi_kts_phu_kien_so.csv)
xem thử 4 cái trước nhé
